import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Upload, Play, Pause, Scissors, Trash2, RotateCcw, RotateCw, Download, Video, Music, Type, Sparkles, Wand2, SlidersHorizontal, Gauge, Plus, ChevronLeft, ChevronRight } from 'lucide-react';

type Clip={id:string;name:string;url:string;duration:number;start:number;speed:number;filter:string;effect:string;transition:string};
type EffectTab='transitions'|'video'|'body';
const transitions=['Clean Cut','Fade to Black','Fade to White','Dissolve','Pull In / Pull Out','Whip Pan','Spin','Tilt Up / Down','Speed Ramp Push','Motion Blur Swipe','Zoom In / Out','Fast Forward Push','RGB Split','Glitch Wave','Static Noise','Pixelate Shift','Flicker','CRT Switch','Glare','Film Burn','Light Leak','Flash','Glow','Bloom','Circle Reveal','Star Reveal','Heart Reveal','Horizontal Banding','Blinds','3D Cube','Page Turn','Collage Swap','Flip Card'];
const videoEffects=['Chromatic Blur','Edge Glow','Flash','Bokeh Lights','Soft Glow','Film Grain','VHS Glitch','Light Leaks','Dust Particles','Polaroid Frames','Retro Camera','Signal Interference','RGB Split','Pixelate','Fish-eye Distortion','Mirror','Rain','Snowfall','Smoke','Fire Rays','Lens Flare','Fog','Motion Blur','Radial Blur','Tilt-Shift Blur','Halo Blur','3D Zoom','Anime Style','Comic Book','Cyberpunk','Oil Painting Overlay'];
const bodyEffects=['Electric Rays','Neon Glow Outline','Lightning Strokes','Laser Aura','Glowing Eyes','Halo Ring','Angel Wings','Demon Horns','Floating Crown','Disappearing Clone','Shadow Trail','RGB Echo','Speed Phantom','Super Saiyan Flame','Particle Burst','Galaxy Sparkles','Cosmic Pulse','Background Matrix','Fire Ring Behind','Grid Aura'];
const filters=['Original','Cinematic','Vintage','Warm','Cool','Retro','B&W','Dramatic'];
const filterCss:Record<string,string>={Original:'none',Cinematic:'contrast(1.18) saturate(1.25)',Vintage:'sepia(.35) contrast(1.1) saturate(.9)',Warm:'sepia(.18) saturate(1.3) hue-rotate(-8deg)',Cool:'saturate(.9) hue-rotate(15deg) brightness(1.05)',Retro:'contrast(1.12) saturate(1.25) sepia(.12)','B&W':'grayscale(1) contrast(1.08)',Dramatic:'contrast(1.3) saturate(1.12) brightness(.96)'};

export default function App(){
 const inputRef=useRef<HTMLInputElement>(null),videoRef=useRef<HTMLVideoElement>(null);
 const [clips,setClips]=useState<Clip[]>([]),[selected,setSelected]=useState<string|null>(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[tab,setTab]=useState<EffectTab>('transitions'),[filter,setFilter]=useState('Original'),[brightness,setBrightness]=useState(0),[contrast,setContrast]=useState(0),[saturation,setSaturation]=useState(0),[speed,setSpeed]=useState(1),[zoom,setZoom]=useState(100),[rotation,setRotation]=useState(0);
 const clip=clips.find(c=>c.id===selected)||clips[0]||null;
 const duration=useMemo(()=>Math.max(1,...clips.map(c=>c.start+c.duration)),[clips]);
 useEffect(()=>{const v=videoRef.current;if(!v)return;const a=()=>setTime(v.currentTime),b=()=>setPlaying(false);v.addEventListener('timeupdate',a);v.addEventListener('ended',b);return()=>{v.removeEventListener('timeupdate',a);v.removeEventListener('ended',b)}},[clip?.url]);
 useEffect(()=>{if(videoRef.current)videoRef.current.playbackRate=speed},[speed]);
 const importFiles=(files:FileList|null)=>{if(!files)return;let start=clips.length?Math.max(...clips.map(c=>c.start+c.duration)):0;Array.from(files).forEach(file=>{if(!file.type.startsWith('video/'))return;const url=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.src=url;v.onloadedmetadata=()=>{const d=Math.min(v.duration||5,60),c:Clip={id:crypto.randomUUID(),name:file.name,url,duration:d,start,speed:1,filter:'Original',effect:'none',transition:'none'};start+=d;setClips(p=>[...p,c]);setSelected(c.id)}})};
 const togglePlay=async()=>{const v=videoRef.current;if(!v)return;if(playing){v.pause();setPlaying(false)}else{await v.play();setPlaying(true)}};
 const seek=(t:number)=>{const v=videoRef.current;if(!v)return;const n=Math.max(0,Math.min(clip?.duration||duration,t));v.currentTime=n;setTime(n)};
 const split=()=>{if(!clip||time<=0||time>=clip.duration)return;const a={...clip,duration:time},b={...clip,id:crypto.randomUUID(),name:clip.name+' — Part 2',start:clip.start+time,duration:clip.duration-time};setClips(p=>p.flatMap(c=>c.id===clip.id?[a,b]:[c]));setSelected(b.id)};
 const remove=()=>{if(!selected)return;setClips(p=>p.filter(c=>c.id!==selected));setSelected(null);setPlaying(false)};
 const applyEffect=(name:string)=>{if(!clip)return;if(tab==='transitions')setClips(p=>p.map(c=>c.id===clip.id?{...c,transition:name}:c));else if(tab==='video')setClips(p=>p.map(c=>c.id===clip.id?{...c,effect:name}:c));else setClips(p=>p.map(c=>c.id===clip.id?{...c,effect:'BODY: '+name}:c))};
 const adjustment=`${filterCss[filter]||'none'} brightness(${1+brightness/100}) contrast(${1+contrast/100}) saturate(${1+saturation/100})`;
 return <div className="h-screen w-screen bg-[#0b0d12] text-white flex flex-col overflow-hidden font-sans">
  <header className="h-12 shrink-0 border-b border-[#242936] bg-[#11141b] flex items-center px-4 gap-4"><div className="text-lg font-black">Clip<span className="text-cyan-400">Forge</span></div><div className="text-xs text-slate-500">Free Creator Video Editor</div><div className="ml-auto flex gap-2"><button onClick={()=>inputRef.current?.click()} className="px-3 py-1.5 rounded bg-cyan-400 text-black text-xs font-bold flex gap-1.5 items-center"><Upload size={14}/>Import</button><button onClick={()=>alert('Browser export renderer will be added next.')} className="px-3 py-1.5 rounded border border-[#303746] text-xs font-semibold flex gap-1.5 items-center"><Download size={14}/>Export</button><input ref={inputRef} type="file" accept="video/*" multiple hidden onChange={e=>importFiles(e.target.files)}/></div></header>
  <main className="flex-1 min-h-0 grid grid-cols-[250px_minmax(0,1fr)_285px]">
   <aside className="border-r border-[#242936] bg-[#10131a] flex flex-col min-h-0"><div className="p-3 border-b border-[#242936] text-xs font-bold uppercase text-slate-400">Media</div><div className="p-3 flex-1 overflow-auto space-y-2">{clips.length===0?<button onClick={()=>inputRef.current?.click()} className="w-full h-28 border border-dashed border-[#394150] rounded-lg text-slate-400 text-xs flex flex-col items-center justify-center gap-2 hover:border-cyan-400"><Plus size={20}/>Add your first video</button>:clips.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full text-left rounded-lg p-2 border ${selected===c.id?'border-cyan-400 bg-cyan-400/10':'border-[#29303c] bg-[#171b23]'}`}><div className="h-20 rounded bg-black overflow-hidden mb-2"><video src={c.url} muted className="w-full h-full object-cover"/></div><div className="text-xs truncate">{c.name}</div><div className="text-[10px] text-slate-500">{c.duration.toFixed(1)}s</div></button>)}</div><div className="grid grid-cols-3 border-t border-[#242936]"><button className="p-3 text-[10px] text-slate-400 flex flex-col items-center gap-1"><Video size={15}/>Video</button><button className="p-3 text-[10px] text-slate-400 flex flex-col items-center gap-1"><Music size={15}/>Audio</button><button className="p-3 text-[10px] text-slate-400 flex flex-col items-center gap-1"><Type size={15}/>Text</button></div></aside>
   <section className="min-w-0 flex flex-col bg-[#0c0f15]"><div className="flex-1 min-h-0 flex items-center justify-center p-6">{clip?<div className="max-h-full max-w-full aspect-video bg-black rounded-lg overflow-hidden border border-[#252b37]"><video ref={videoRef} src={clip.url} onClick={togglePlay} className="w-full h-full object-contain" style={{filter:adjustment,transform:`scale(${zoom/100}) rotate(${rotation}deg)`}}/></div>:<div className="text-center text-slate-500"><Sparkles className="mx-auto mb-3" size={34}/><div className="text-sm">Import a video to start editing</div></div>}</div><div className="h-14 shrink-0 border-t border-[#242936] flex items-center justify-center gap-3"><button onClick={()=>seek(time-.1)} className="p-2"><ChevronLeft size={17}/></button><button onClick={togglePlay} disabled={!clip} className="w-9 h-9 rounded-full bg-white text-black flex items-center justify-center disabled:opacity-30">{playing?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}</button><button onClick={()=>seek(time+.1)} className="p-2"><ChevronRight size={17}/></button><span className="font-mono text-xs text-slate-400">{time.toFixed(2)} / {duration.toFixed(2)}</span></div></section>
   <aside className="border-l border-[#242936] bg-[#10131a] min-h-0 flex flex-col"><div className="grid grid-cols-3 border-b border-[#242936]">{(['transitions','video','body'] as EffectTab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`py-3 text-[10px] font-bold uppercase ${tab===t?'text-cyan-300 border-b-2 border-cyan-400':'text-slate-500'}`}>{t==='video'?'Video FX':t==='body'?'Body FX':'Transitions'}</button>)}</div><div className="flex-1 overflow-auto p-3 space-y-2">{(tab==='transitions'?transitions:tab==='video'?videoEffects:bodyEffects).map(name=><button key={name} onClick={()=>applyEffect(name)} className="w-full text-left px-3 py-2.5 rounded border border-[#252c38] bg-[#151922] hover:border-cyan-400 hover:bg-cyan-400/10 text-xs flex items-center justify-between"><span>{name}</span><Wand2 size={13} className="text-slate-600"/></button>)}</div></aside>
  </main>
  <section className="h-[270px] shrink-0 border-t border-[#242936] bg-[#11141b] flex flex-col"><div className="h-10 border-b border-[#242936] flex items-center gap-1 px-3"><button onClick={split} className="px-2.5 py-1.5 rounded bg-[#1b202a] text-xs flex gap-1.5 items-center"><Scissors size={14}/>Split</button><button onClick={remove} className="px-2.5 py-1.5 rounded bg-[#1b202a] text-xs text-red-300 flex gap-1.5 items-center"><Trash2 size={14}/>Delete</button><button onClick={()=>setRotation(r=>r-90)} className="p-1.5 rounded bg-[#1b202a]"><RotateCcw size={14}/></button><button onClick={()=>setRotation(r=>r+90)} className="p-1.5 rounded bg-[#1b202a]"><RotateCw size={14}/></button><div className="ml-auto text-xs text-slate-500">Timeline • {clips.length} clips</div></div><div className="flex-1 min-h-0 overflow-auto p-3"><div className="min-w-[900px]"><div className="h-6 flex text-[10px] text-slate-600 font-mono border-b border-[#242936]">{Array.from({length:12},(_,i)=><span key={i} className="w-24">{i}s</span>)}</div><div className="mt-2 space-y-2">{clips.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`relative block h-12 rounded border text-left overflow-hidden ${selected===c.id?'border-cyan-400':'border-[#343b48]'} bg-[#1b2430]`} style={{marginLeft:c.start*60,width:Math.max(120,c.duration*60)}}><div className="absolute inset-0 opacity-35 bg-gradient-to-r from-cyan-500 to-blue-500"/><div className="relative px-2 py-1 text-[11px] font-semibold truncate">{c.name}</div><div className="relative px-2 text-[9px] text-slate-300">{c.effect!=='none'?c.effect:c.transition!=='none'?c.transition:'Video'}</div></button>)}</div></div></div></section>
  <section className="h-40 shrink-0 border-t border-[#242936] bg-[#0e1117] px-4 py-3 grid grid-cols-4 gap-4"><div><div className="text-[10px] uppercase text-slate-500 mb-2 flex items-center gap-1"><SlidersHorizontal size={12}/>Filters</div><div className="flex flex-wrap gap-1">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-2 py-1 rounded text-[10px] ${filter===f?'bg-cyan-400 text-black':'bg-[#1b202a] text-slate-300'}`}>{f}</button>)}</div></div><div><div className="text-[10px] uppercase text-slate-500 mb-2">Adjust</div>{[['Brightness',brightness,setBrightness],['Contrast',contrast,setContrast],['Saturation',saturation,setSaturation]].map(([n,v,setter]:any)=><label key={n} className="flex items-center gap-2 text-[10px] text-slate-400 mb-2"><span className="w-16">{n}</span><input type="range" min="-100" max="100" value={v} onChange={e=>setter(Number(e.target.value))} className="flex-1 accent-cyan-400"/></label>)}</div><div><div className="text-[10px] uppercase text-slate-500 mb-2 flex items-center gap-1"><Gauge size={12}/>Speed</div><input type="range" min="0.25" max="4" step="0.25" value={speed} onChange={e=>setSpeed(Number(e.target.value))} className="w-full accent-cyan-400"/><div className="text-xs text-slate-300 mt-1">{speed}×</div><div className="flex gap-1 mt-2">{[.5,1,1.5,2,4].map(x=><button key={x} onClick={()=>setSpeed(x)} className="px-2 py-1 rounded bg-[#1b202a] text-[10px]">{x}×</button>)}</div></div><div><div className="text-[10px] uppercase text-slate-500 mb-2">Transform</div><label className="text-[10px] text-slate-400">Zoom <input type="range" min="50" max="160" value={zoom} onChange={e=>setZoom(Number(e.target.value))} className="w-full accent-cyan-400"/></label><div className="text-xs mt-1 text-slate-300">{zoom}% • {rotation}°</div><div className="mt-3 text-[10px] text-slate-500">No watermark • No premium lock</div></div></section>
 </div>
}